spring:
  datasource:
    druid:
      url: jdbc:mysql://测试数据库IP:3306/starlink_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: 测试库用户名
      password: 测试库密码
      max-active: 50
  data:
    redis:
      host: 测试RedisIP
      port: 6379
      database: 1

# 测试环境也关闭 MyBatis SQL 日志（减轻压力）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLogImpl
